BTL_Nhom8/BTL_Nhom8/Controllers/CartController.cs
using BTL_Nhom8.Dto;
using BTL_Nhom8.Helper;
using BTL_Nhom8.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace BTL_Nhom8.Controllers
{
    [MyFilter]
    public class CartController : Controller
    {

        // GET: Cart
        private Web_Tranh_Theu db = new Web_Tranh_Theu();
        private const string CartSession = "CartSession";

        public ActionResult Index()
        {
            var cart = (Cart)Session[CartSession];
            if (cart == null || cart.cartLines.Count == 0)
            {
                ViewBag.Message = "Giỏ hàng trống";
            }
            return View(cart);

        }

        [HttpPost]
        public ActionResult AddItem(int product_Id, int quantity)
        {
            if (Session["HoTen"] == null)
            {
                return Redirect("/Home/Login");
            }
            else
            {
                var cart = (Cart)Session[CartSession];
                if (cart == null)
                {
                    cart = new Cart();
                }

                if (cart.cartLines.Exists(x => x.productDto.Id == product_Id))
                {
                    var item = cart.cartLines.Find(x => x.productDto.Id == product_Id);
                     int slt = db.Products.Find(product_Id).Quantity;
                      if (item.quantity + quantity > slt)
                          item.quantity = slt;
                      else item.quantity += quantity; 
                }
                else
                {
                    Product product = db.Products.Find(product_Id);
                    ProductDto productDto = new ProductDto(product);
                    cart.cartLines.Add(new CartItem(productDto,quantity));
                }
                Session[CartSession] = cart;
                Session["CartLineTotal"] = cart.cartLines.Count();
            }
            return RedirectToAction("Index");
        }
        public ActionResult EditItem(int id, int quantity)
        {
            var cart = (Cart) Session[CartSession];
            string sl = "";
            var item = cart.cartLines.FirstOrDefault(x => x.productDto.Id == id);
            item.quantity = quantity;
            sl = Convert.ToDecimal(item.getAmount()).ToString("#,#");
            return Json(new
            {
                status = true, sl
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteItem(int id)
        {
            var cart = (Cart)Session[CartSession];
            var item = cart.cartLines.Find(p => p.productDto.Id.Equals(id));
            if(item != null)
            {
                cart.cartLines.Remove(item);
                @Session["CartLineTotal"] = (int)cart.cartLines.Count;
            }
            Session[CartSession] = cart;
            return Json(new
            {
                status = true,
                cartline = @Session["CartLineTotal"]
            }, JsonRequestBehavior.AllowGet); 
        }

        public ActionResult DeleteAllItem()
        {
            var cart = (Cart)Session[CartSession];
            cart.cartLines.RemoveAll(p => p.getAmount() > 1);

            Session[CartSession] = cart;
            Session["CartLineTotal"] = 0;
            return Json(new
            {
                status = true
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

BTL_Nhom8/BTL_Nhom8/Controllers/CheckoutController.cs
using BTL_Nhom8.Dto;
using BTL_Nhom8.Helper;
using BTL_Nhom8.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace BTL_Nhom8.Controllers
{
    [MyFilter]
    public class CheckoutController : Controller
    {
        private Web_Tranh_Theu db = new Web_Tranh_Theu();
        private const string CartSession = "CartSession";

        [HttpPost]
        public ActionResult Items_Error(string CartItems)
        {

            var cart = (Cart)Session[CartSession];
            if (cart == null || cart.cartLines.Count == 0)
            {
                return RedirectToAction("index");
            }
            var jsonCartItem = new JavaScriptSerializer().Deserialize<List<CartItem>>(CartItems);
            List<ItemError> itemErrors = new List<ItemError>();
            foreach (var item in jsonCartItem)
            {
                int sltQuantity = db.Products.Where(x => x.Product_Id == item.productDto.Id).Select(x => x.Quantity).SingleOrDefault();

                if (item.quantity > sltQuantity)
                {
                    var i = cart.cartLines.SingleOrDefault(x => x.productDto.Id == item.productDto.Id);
                    itemErrors.Add(new ItemError(i.productDto, sltQuantity, item.quantity));
                }
            }
            if (itemErrors.Count > 0)
            {
                return View(itemErrors);
            }
            else
            {
                int id_user = (int)Session["idUser"];
                Account acc = (Account)db.Accounts.Where(a => a.Account_Id.Equals(id_user)).First();
                cart.customerDto = new CustomerDto(acc);
                Session[CartSession] = cart;
                return RedirectToAction("Index");
            }
        }
        
        public ActionResult Index()
        {
            var cart = (Cart)Session[CartSession];
            if (cart == null || cart.cartLines.Count == 0)
            {
                return Redirect("/Cart/Index");
            }
            return View(cart);

        }

        [HttpPost]
        public ActionResult Final_Checkout(CustomerDto customerDto)
        {

            var cart = (Cart)Session[CartSession];

            if (cart.cartLines.Count < 1)
            {
                return Redirect("/Cart/Index");
            }
            if (ModelState.IsValid)
            {
                Order order = new Order();
                order.Account_Id = (int)Session["idUser"];
                order.Customer_Address = customerDto.Address;
                order.Customer_Phone = customerDto.Telephone;
                order.Status = true;
                order.Order_Date = DateTime.Now;
                order.Total_Amount = ((long)cart.cartLines.Sum(x => x.getAmount()));
                db.Orders.Add(order);
                foreach (var item in cart.cartLines)
                {
                    var product = db.Products.Find(item.productDto.Id);
                    product.Quantity -= item.quantity;
                    db.Entry(product).State = EntityState.Modified;
                    DetailProduct_Order detail = new DetailProduct_Order();
                    detail.Order_Id = order.Order_Id;
                    detail.Product_Id = item.productDto.Id;
                    detail.Order_Quantity = item.quantity;
                    detail.Order_Price = item.productDto.Price;
                    db.DetailProduct_Order.Add(detail);  
                }
                db.SaveChanges();
                cart.cartLines.RemoveAll(x => x.getAmount() > 0);
                Session["CartLineTotal"] = 0;
                Session.Remove(CartSession);
                return View(cart);
            }
            cart.customerDto = customerDto;
            return View("Index",cart);
        }

    }
}

BTL_Nhom8/BTL_Nhom8/Views/Checkout/Final_Checkout.cshtml
@model BTL_Nhom8.Dto.Cart
@{
    ViewBag.Title = "Final_Checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="breadcrumb-area">
    <!-- Top Breadcrumb Area -->
    <div class="top-breadcrumb-area bg-img bg-overlay d-flex align-items-center justify-content-center"
         style="background-image: url(/wwwroot/img/bg-img/24.jpg);">
        <h2>Sản phẩm</h2>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Trang chủ</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Cửa hàng</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<br />
<br />
<h1 style="color:red; font:bolder">Thanh toán thành công</h1>
<br />
<br />

BTL_Nhom8/BTL_Nhom8/Views/Checkout/Index.cshtml
@model BTL_Nhom8.Dto.Cart

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- ##### Breadcrumb Area Start ##### -->
<div class="breadcrumb-area">
    <!-- Top Breadcrumb Area -->
    <div class="top-breadcrumb-area bg-img bg-overlay d-flex align-items-center justify-content-center" style="background-image: url(/wwwroot/img/bg-img/24.jpg);">
        <h2>Thủ tục thanh toán</h2>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Trang chủ</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Thủ tục thanh toán</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- ##### Breadcrumb Area End ##### -->
<!-- ##### Checkout Area Start ##### -->
<div class="checkout_area mb-100">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-12 col-lg-7">
                <div class="checkout_details_area clearfix">
                    <h5>Chi tiết thanh toán</h5>
                    @using (Html.BeginForm("Final_Checkout", "Checkout", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                <div class="col-12 mb-4">
                                    <label for="email_address">Địa chỉ email *</label>
                                    <input type="email" class="form-control" name="Email" id="email_address" value="@Model.customerDto.Email" readonly="readonly">
                                </div>

                                <div class="col-12 mb-4">
                                    <label for="customers">Tên khách hàng *</label>
                                    <input type="text" class="form-control" name="Customer_Name" id="customers" value="@Model.customerDto.Customer_Name" readonly="readonly">
                                </div>

                                <div class="col-12 mb-4">
                                    <label for="tel">Số điện thoại *</label>
                                    <input type="text" class="form-control" name="Telephone" id="tel" value="@Model.customerDto.Telephone" required>
                                    @Html.ValidationMessageFor(model => Model.customerDto.Telephone, "", new { @class = "text-danger" })
                                </div>

                                <div class="col-12 mb-4">
                                    <label for="company">Địa chỉ *</label>
                                    <input type="text" class="form-control" name="Address" id="company" value="@Model.customerDto.Address" required>
                                    @Html.ValidationMessageFor(model => Model.customerDto.Address, "", new { @class = "text-danger"})
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="mt-3">
                                    <button type="submit" class="btn btn-warning">Đặt hàng</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>

            <div class="col-12 col-lg-4">
                <div class="checkout-content">
                    <h5 class="title--">Đơn hàng của bạn</h5>
                    <div class="products">
                        <div class="products-data">
                            <h5>Các sản phẩm:</h5>
                            @{ var price = "";}
                            @foreach (var item in Model.cartLines)
                            {
                                <div class="single-products d-flex justify-content-between align-items-center">

                                    <p>@item.productDto.Name</p>
                                    <h5>@{price = Convert.ToDecimal(item.productDto.Price).ToString("#,#");}@price</h5>


                                </div>
                            }
                        </div>
                    </div>
                    <div class="subtotal d-flex justify-content-between align-items-center">
                        <h5>Tổng loại hàng:</h5>
                        <h5>@(Model.cartLines.Count())</h5>
                    </div>
                    <div class="subtotal d-flex justify-content-between align-items-center">
                        <h5>Tổng số lượng sản phẩm mua</h5>
                        <h5>@(Model.cartLines.Sum(x=>x.quantity))</h5>
                    </div>

                    <div class="order-total d-flex justify-content-between align-items-center">
                        <h5>Tổng hóa đơn</h5>
                        @{price = Convert.ToDecimal(Model.cartLines.Sum(item => item.getAmount())).ToString("#,# VNĐ"); }
                        <h5>@price</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Checkout Area End ##### -->

BTL_Nhom8/BTL_Nhom8/Views/Checkout/Items_Error.cshtml
@model IEnumerable<BTL_Nhom8.Dto.ItemError>
@{
    ViewBag.Title = "Items_Error";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="breadcrumb-area">
    <!-- Top Breadcrumb Area -->
    <div class="top-breadcrumb-area bg-img bg-overlay d-flex align-items-center justify-content-center"
         style="background-image: url(/wwwroot/img/bg-img/24.jpg);">
        <h2>Sản phẩm</h2>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Trang chủ</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Cart")">Giỏ hàng</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Sản phẩm lỗi</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<br />
<br />
<div class="container">
    <h2>Sản phẩm đặt hàng lỗi</h2>
    <p>Danh sách các mặt hàng có số lượng đặt lớn hơn số lượng có trong kho:</p>
    <table class="table">
        <thead>
            <tr>
                <th>Ảnh</th>
                <th>Tên</th>
                <th>Price</th>
                <th>Số lượng</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td><img src="~/wwwroot/img/Images/@item.productDto.Avatar" width="100" height="100" /></td>
                    <td>@item.productDto.Name</td>
                    <td>@item.productDto.Price</td>
                    <td>@item.slOrder -> @item.slt</td>
                </tr>
            }

        </tbody>
    </table>
</div>