BTL_Nhom8/BTL_Nhom8/Areas/Admin/Controllers/OrderController.cs
using BTL_Nhom8.Areas.Admin.Dto;
using BTL_Nhom8.Helper;
using BTL_Nhom8.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_Nhom8.Areas.Admin.Controllers
{
    [FilterAdmin]
    public class OrderController : Controller
    {
        // GET: Admin/Order
        Web_Tranh_Theu db = new Web_Tranh_Theu();
        public static List<OrderDto> orders;
        public ActionResult Index()
        {
            orders  =
            ((List<OrderDto>)(from s in db.Orders
            join r in db.Accounts on s.Account_Id equals r.Account_Id
            select new OrderDto()
            {
                Order_Id = s.Order_Id,
                Customer_Name = r.Customer_Name,
                Customer_Address = s.Customer_Address,
                Customer_Phone = s.Customer_Phone ,
                Order_Date = s.Order_Date.ToString(),
                Customer_Email = r.Email,
                Total_Amount = s.Total_Amount,
                Status = s.Status
            }).ToList());
            return View(orders);
        }
        public ActionResult Order_Detail(int? orderId)
        {
            if(orderId == null)
            {
                return RedirectToAction("Index");
            }
            OrderDto orderDto = orders.Find(o => o.Order_Id == orderId);
            List<OrderDetailDto> orderDetails =
            ((List<OrderDetailDto>)(from s in db.DetailProduct_Order
                              join r in db.Products on s.Product_Id equals r.Product_Id
                              where(s.Order_Id == orderId)
                              select new OrderDetailDto()
                              {
                                  Product_Name = r.Name,
                                  Product_Price = s.Order_Price,
                                  Product_Quantity = s.Order_Quantity
                              }).ToList());
          
            ViewBag.Order = orderDto;
            return View(orderDetails);
        }

        public ActionResult Order_Edit(int? orderId)
        {
            if (orderId == null)
            {
                return RedirectToAction("Index");
            }
            OrderDto orderDto = orders.Find(o => o.Order_Id == orderId);
            return View(orderDto);
        }

        [HttpPost]
        public ActionResult Order_Edit(OrderDto orderDto)
        {
            if (ModelState.IsValid)
            {
                Order order = db.Orders.Find(orderDto.Order_Id);
                order.Customer_Address = orderDto.Customer_Address;
                order.Customer_Phone = orderDto.Customer_Phone;
                order.Status = orderDto.Status;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(orderDto);
                
        }
    }
}

BTL_Nhom8/BTL_Nhom8/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BTL_Nhom8.Models;

namespace BTL_Nhom8.Controllers
{
    public class NewsController : Controller
    {
        private Web_Tranh_Theu db = new Web_Tranh_Theu();

        // GET: News
        public ActionResult Index()
        {
            return View(db.News.ToList());
        }

        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

       
    }
}

BTL_Nhom8/BTL_Nhom8/Areas/Admin/Views/Shared/_ButtonFoot.cshtml
<div class="fixed-button">
    <a href="https://codedthemes.com/item/guru-able-admin-template/" target="_blank"
       class="btn btn-md btn-primary">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i> Upgrade To Pro
    </a>
</div>

BTL_Nhom8/BTL_Nhom8/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>GURU Able - Free Lite Admin Template </title>
    <!-- HTML5 Shim and Respond.js IE9 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="CodedThemes">
    <meta name="keywords"
          content=" Admin , Responsive, Landing, Bootstrap, App, Template, Mobile, iOS, Android, apple, creative app">
    <meta name="author" content="CodedThemes">
    <!-- Favicon icon -->
    <link rel="icon" href="~/Areas/Admin/Assets/images/favicon.ico" type="image/x-icon">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet">
    <!-- Required Fremwork -->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/Assets/css/bootstrap/css/bootstrap.min.css">
    <!-- themify-icons line icon -->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/Assets/icon/themify-icons/themify-icons.css">
    <!-- ico font -->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/Assets/icon/icofont/css/icofont.css">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/Assets/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/Areas/Admin/Assets/css/jquery.mCustomScrollbar.css">
</head>

<body>
    <!-- Pre-loader start -->
    <div class="theme-loader">
        <div class="ball-scale">
            <div class='contain'>
                <div class="ring">
                    <div class="frame"></div>
                </div>
                <div class="ring">
                    <div class="frame"></div>
                </div>
                <div class="ring">

                    <div class="frame"></div>
                </div>
                <div class="ring">
                    <div class="frame"></div>
                </div>
                <div class="ring">
                    <div class="frame"></div>
                </div>
                <div class="ring">
                    <div class="frame"></div>
                </div>
                <div class="ring">
                    <div class="frame"></div>
                </div>
                <div class="ring">
                    <div class="frame"></div>
                </div>
                <div class="ring">
                    <div class="frame"></div>
                </div>
                <div class="ring">
                    <div class="frame"></div>
                </div>
            </div>
        </div>
    </div>
    <!-- Pre-loader end -->
    <div id="pcoded" class="pcoded">
        <div class="pcoded-overlay-box"></div>
        <div class="pcoded-container navbar-wrapper">

            @{ Html.RenderPartial("_MenuTop");}
            <div class="pcoded-main-container">
                <div class="pcoded-wrapper">
                    <!-- menu left -->

                    @{ Html.RenderPartial("_MenuLeft");}

                    <!-- menu left -->
                    @RenderBody()
                </div>
            </div>
            @{ Html.RenderPartial("_ButtonFoot");}
        </div>
    </div>

    <!-- Required Jquery -->
    <script type="text/javascript" src="~/Areas/Admin/Assets/js/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/Areas/Admin/Assets/js/jquery-ui/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/Areas/Admin/Assets/js/popper.js/popper.min.js"></script>
    <script type="text/javascript" src="~/Areas/Admin/Assets/js/bootstrap/js/bootstrap.min.js"></script>
    <!-- jquery slimscroll js -->
    <script type="text/javascript" src="~/Areas/Admin/Assets/js/jquery-slimscroll/jquery.slimscroll.js"></script>
    <!-- modernizr js -->
    <script type="text/javascript" src="~/Areas/Admin/Assets/js/modernizr/modernizr.js"></script>
    <!-- am chart -->
    <script src="~/Areas/Admin/Assets/pages/widget/amchart/amcharts.min.js"></script>
    <script src="~/Areas/Admin/Assets/pages/widget/amchart/serial.min.js"></script>
    <!-- Todo js -->
    <script type="text/javascript " src="~/Areas/Admin/Assets/pages/todo/todo.js "></script>
    <!-- Custom js -->
    <script type="text/javascript" src="~/Areas/Admin/Assets/pages/dashboard/custom-dashboard.js"></script>
    <script type="text/javascript" src="~/Areas/Admin/Assets/js/script.js"></script>
    <script type="text/javascript " src="~/Areas/Admin/Assets/js/SmoothScroll.js"></script>
    <script src="~/Areas/Admin/Assets/js/pcoded.min.js"></script>
    <script src="~/Areas/Admin/Assets/js/demo-12.js"></script>
    <script type="text/javascript" src="~/Areas/Admin/Assets/js/modernizr/modernizr.js"></script>
    @*<script type="text/javascript" src="~/Areas/Admin/Assets/js/modernizr/css-scrollbars.js"></script>*@
    <script src="~/Areas/Admin/Assets/js/common-pages.js"></script>
    <script src="~/Areas/Admin/Assets/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script>
        var $window = $(window);
        var nav = $('.fixed-button');
        $window.scroll(function () {
            if ($window.scrollTop() >= 200) {
                nav.addClass('active');
            }
            else {
                nav.removeClass('active');
            }
        });</script>
    <script src="~/wwwroot/js/DeleteCategory.js"></script>
    <script src="~/wwwroot/js/DeleteProduct.js"></script>
    <script src="~/wwwroot/js/Account.js"></script>

</body>

</html>

BTL_Nhom8/BTL_Nhom8/Areas/Admin/Views/Shared/_MenuLeft.cshtml
<nav class="pcoded-navbar">
    <div class="sidebar_toggle"><a href="#"><i class="icon-close icons"></i></a></div>
    <div class="pcoded-inner-navbar main-menu">
        <div class="">
            <div class="main-menu-header">
                <img class="img-40 img-radius" src="~/Areas/Admin/Assets/images/avatar-4.jpg"
                     alt="User-Profile-Image">
                <div class="user-details">
                    <span>@Session["UserName"]</span>
                    <span id="more-details">@Session["Email"]<i class="ti-angle-down"></i></span>
                </div>
            </div>

            <div class="main-menu-content">
                <ul>
                    <li class="more-details">
                        <a href="#"><i class="ti-user"></i>Xem trang cá nhân</a>
                        <a href="#!"><i class="ti-settings"></i>Cài đặt</a>
                        <a href="@Url.Action("Logout", "Home")">
                            <i class="ti-layout-sidebar-left"></i>Đăng xuất
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="pcoded-search">
            <span class="searchbar-toggle"> </span>
            <div class="pcoded-search-box ">
                <input type="text" placeholder="Tìm kiếm">
                <span class="search-icon"><i class="ti-search" aria-hidden="true"></i></span>
            </div>
        </div>
        <div class="pcoded-navigatio-lavel" data-i18n="nav.category.navigation">Quản lý</div>
        <ul class="pcoded-item pcoded-left-item">
            <li class="active">
                <a href="@Url.Action("Index", "Home")">
                    <span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
                    <span class="pcoded-mtext" data-i18n="nav.dash.main">Bảng diều khiển</span>
                    <span class="pcoded-mcaret"></span>
                </a>
            </li>
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="ti-layout-grid2-alt"></i></span>
                    <span class="pcoded-mtext" data-i18n="nav.basic-components.main">
                        Quản lý danh
                        mục SP
                    </span>
                    <span class="pcoded-mcaret"></span>
                </a>
                <ul class="pcoded-submenu">
                    <li class=" ">
                        <a href="@Url.Action("Add_Category", "Category")">
                            <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                            <span class="pcoded-mtext" data-i18n="nav.basic-components.alert">
                                Thêm
                                danh mục
                            </span>
                            <span class="pcoded-mcaret"></span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="@Url.Action("Index", "Category")">
                            <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                            <span class="pcoded-mtext"
                                  data-i18n="nav.basic-components.breadcrumbs">
                                Danh sách danh
                                mục
                            </span>
                            <span class="pcoded-mcaret"></span>
                        </a>
                    </li>

                </ul>
            </li>
            <!-- 1 -->
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="ti-layout-grid2-alt"></i></span>
                    <span class="pcoded-mtext" data-i18n="nav.basic-components.main">
                        Quản lý sản
                        phẩm
                    </span>
                    <span class="pcoded-mcaret"></span>
                </a>
                <ul class="pcoded-submenu">
                    <li class=" ">
                        <a href="@Url.Action("Add_Product", "Product")">
                            <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                            <span class="pcoded-mtext" data-i18n="nav.basic-components.alert">
                                Thêm
                                sản phẩm
                            </span>
                            <span class="pcoded-mcaret"></span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="@Url.Action("Index", "Product")">
                            <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                            <span class="pcoded-mtext"
                                  data-i18n="nav.basic-components.breadcrumbs">
                                Danh sách sản
                                phẩm
                            </span>
                            <span class="pcoded-mcaret"></span>
                        </a>
                    </li>

                </ul>
            </li>
            <!-- 2 -->
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="ti-layout-grid2-alt"></i></span>
                    <span class="pcoded-mtext" data-i18n="nav.basic-components.main">
                        Quản lý tài
                        khoản
                    </span>
                    <span class="pcoded-mcaret"></span>
                </a>
                <ul class="pcoded-submenu">
                    <li class=" ">
                        <a href="@Url.Action("Add_Account", "Account")">
                            <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                            <span class="pcoded-mtext" data-i18n="nav.basic-components.alert">
                                Thêm
                                tài khoản
                            </span>
                            <span class="pcoded-mcaret"></span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="@Url.Action("Index", "Account")">
                            <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                            <span class="pcoded-mtext"
                                  data-i18n="nav.basic-components.breadcrumbs">
                                Danh sách tài
                                khoản
                            </span>
                            <span class="pcoded-mcaret"></span>
                        </a>
                    </li>

                </ul>
            </li>
            <!-- 3 -->
            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="ti-layout-grid2-alt"></i></span>
                    <span class="pcoded-mtext" data-i18n="nav.basic-components.main">
                        Quản lý đơn
                        hàng
                    </span>
                    <span class="pcoded-mcaret"></span>
                </a>
                <ul class="pcoded-submenu">

                    <li class=" ">
                        <a href="@Url.Action("Index", "Order")">
                            <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                            <span class="pcoded-mtext"
                                  data-i18n="nav.basic-components.breadcrumbs">
                                Danh sách đơn đặt
                                hàng
                            </span>
                            <span class="pcoded-mcaret"></span>
                        </a>
                    </li>

                </ul>
            </li>




            <li class="pcoded-hasmenu">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="ti-layout-grid2-alt"></i></span>
                    <span class="pcoded-mtext" data-i18n="nav.basic-components.main">
                        Quản lý bài viết
                    </span>
                    <span class="pcoded-mcaret"></span>
                </a>
                <ul class="pcoded-submenu">
                    <li class=" ">
                        <a href="@Url.Action("Create", "News")">
                            <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                            <span class="pcoded-mtext" data-i18n="nav.basic-components.alert">
                                Thêm
                                bài viết
                            </span>
                            <span class="pcoded-mcaret"></span>
                        </a>
                    </li>
                    <li class=" ">
                        <a href="@Url.Action("Index", "News")">
                            <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                            <span class="pcoded-mtext"
                                  data-i18n="nav.basic-components.breadcrumbs">
                                Danh sách bài viết
                            </span>
                            <span class="pcoded-mcaret"></span>
                        </a>
                    </li>

                </ul>
            </li>




        </ul>

    </div>
</nav>

BTL_Nhom8/BTL_Nhom8/Areas/Admin/Views/Shared/_MenuTop.cshtml
<nav class="navbar header-navbar pcoded-header">
    <div class="navbar-wrapper">

        <div class="navbar-logo">
            <a class="mobile-menu" id="mobile-collapse" href="#!">
                <i class="ti-menu"></i>
            </a>
            <a class="mobile-search morphsearch-search" href="#">
                <i class="ti-search"></i>
            </a>
            <a href="index.html">
                <img class="img-fluid" src="~/Areas/Admin/Assets/images/logo.png" alt="Theme-Logo" />
            </a>
            <a class="mobile-options">
                <i class="ti-more"></i>
            </a>
        </div>

        <div class="navbar-container container-fluid">
            <ul class="nav-left">
                <li>
                    <div class="sidebar_toggle">
                        <a href="javascript:void(0)"><i class="ti-menu"></i></a>
                    </div>
                </li>

                <li>
                    <a href="#!" onclick="javascript:toggleFullScreen()">
                        <i class="ti-fullscreen"></i>
                    </a>
                </li>
            </ul>
            <ul class="nav-right">
                <li class="header-notification">
                    <a href="#!">
                        <i class="ti-bell"></i>
                        <span class="badge bg-c-pink"></span>
                    </a>
                    <ul class="show-notification">
                        <li>
                            <h6>Thông báo</h6>
                            <label class="label label-danger">Mới</label>
                        </li>
                        <li>
                            <div class="media">
                                <img class="d-flex align-self-center img-radius"
                                     src="~/Areas/Admin/Assets/images/avatar-4.jpg" alt="Generic placeholder image">
                                <div class="media-body">
                                    <h5 class="notification-user">Ngô Văn Hiệp</h5>
                                    <p class="notification-msg">
                                        Xin chào
                                    </p>
                                    <span class="notification-time">30 phút trước</span>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="media">
                                <img class="d-flex align-self-center img-radius"
                                     src="~/Areas/Admin/Assets/images/avatar-3.jpg" alt="Generic placeholder image">
                                <div class="media-body">
                                    <h5 class="notification-user">Ngô Văn Hiệp</h5>
                                    <p class="notification-msg">
                                        Xin chào
                                    </p>
                                    <span class="notification-time">30 phút trước</span>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="media">
                                <img class="d-flex align-self-center img-radius"
                                     src="~/Areas/Admin/Assets/images/avatar-4.jpg" alt="Generic placeholder image">
                                <div class="media-body">
                                    <h5 class="notification-user">Ngô Văn Hiệp</h5>
                                    <p class="notification-msg">
                                        Xin chào
                                    </p>
                                    <span class="notification-time">30 phút trước</span>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="user-profile header-notification">
                    <a href="#!">
                        <img src="~/Areas/Admin/Assets/images/avatar-4.jpg" class="img-radius" alt="User-Profile-Image">
                        <span>@Session["UserName"]</span>
                        <i class="ti-angle-down"></i>
                    </a>
                    <ul class="show-notification profile-notification">
                        <li>
                            <a href="#!">
                                <i class="ti-settings"></i> Cài đặt
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="ti-user"></i> Thông tin tài khoản
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="ti-email"></i> Tin nhắn
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="ti-lock"></i> Khóa màn hình
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Logout", "Home")">
                                <i class="ti-layout-sidebar-left"></i> Đăng xuất
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>